# Generated by Django 4.1.1 on 2023-01-24 12:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pay",
            fields=[
                (
                    "EDP_BILL_NO",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ՎՃարման ID",
                    ),
                ),
                (
                    "EDP_AMOUNT",
                    models.CharField(
                        default="1.00", max_length=16, verbose_name="Գումար"
                    ),
                ),
                (
                    "EDP_REC_ACCOUNT",
                    models.CharField(
                        default="110001952", max_length=16, verbose_name="Ստացողի ID"
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(default=False, verbose_name="Հաստատված է"),
                ),
            ],
            options={
                "verbose_name": "ՎՃարումներ",
                "verbose_name_plural": "ՎՃարումներ",
            },
        ),
    ]
