# Generated by Django 4.1.1 on 2023-03-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("primaries_app", "0002_alter_payviaimage_voter_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="markmodel",
            options={
                "verbose_name": "Վստահություն հայտնելու չափորոշիչ",
                "verbose_name_plural": "Վստահություն հայտնելու չափորոշիչներ",
            },
        ),
    ]
