# Generated by Django 4.1.1 on 2023-01-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default=None, max_length=30, unique=True, verbose_name="էլ․ հաստցէ"
            ),
            preserve_default=False,
        ),
    ]
