# Generated by Django 4.1.1 on 2023-01-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=70, unique=True, verbose_name="էլ․ հաստցէ"
            ),
        ),
    ]
