# Generated by Django 4.1.1 on 2023-01-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=2000,
                null=True,
                verbose_name="օգտանուն",
            ),
        ),
    ]
