# Generated by Django 4.1.1 on 2023-03-02 17:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="additional_url",
            field=models.URLField(
                blank=True,
                help_text="Additional url",
                max_length=300,
                null=True,
                validators=[accounts.models.validate_url],
                verbose_name="Լրացուցիչ հղում",
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="facebook_url",
            field=models.URLField(
                help_text="Facebook account url",
                max_length=300,
                validators=[accounts.models.validate_url],
                verbose_name="Facebook Հղում",
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                help_text="Youtube account url",
                max_length=300,
                null=True,
                validators=[accounts.models.validate_url],
                verbose_name="YouTube Հղում",
            ),
        ),
        migrations.AlterField(
            model_name="voterprofile",
            name="already_voted",
            field=models.BooleanField(default=False, verbose_name="Արդեն քվեարկել է"),
        ),
        migrations.AlterField(
            model_name="voterprofile",
            name="soc_url",
            field=models.URLField(
                max_length=300,
                validators=[accounts.models.validate_url],
                verbose_name="Սոցիալական կայքի հղում",
            ),
        ),
        migrations.AlterField(
            model_name="voterprofile",
            name="votes_count",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="Քվեների քանակ"
            ),
        ),
    ]
