# Generated by Django 4.1.1 on 2023-03-02 18:56

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_candidateprofile_additional_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatepost",
            name="media_path",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Տեսահոլովակի հղում"
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="additional_url",
            field=models.CharField(
                blank=True,
                help_text="Additional url",
                max_length=300,
                null=True,
                validators=[accounts.models.validate_url],
                verbose_name="Լրացուցիչ հղում",
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="facebook_url",
            field=models.CharField(
                help_text="Facebook account url",
                max_length=300,
                validators=[accounts.models.validate_url],
                verbose_name="Facebook Հղում",
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="youtube_url",
            field=models.CharField(
                blank=True,
                help_text="Youtube account url",
                max_length=300,
                null=True,
                validators=[accounts.models.validate_url],
                verbose_name="YouTube Հղում",
            ),
        ),
        migrations.AlterField(
            model_name="voterprofile",
            name="soc_url",
            field=models.CharField(
                max_length=300,
                validators=[accounts.models.validate_url],
                verbose_name="Սոցիալական կայքի հղում",
            ),
        ),
    ]
